spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/ordersdb_dev
  username: meli_user
  password: meli2025
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate:
    ddl-auto: update
    show-sql: true
server:
 port: 8080