spring:
 datasource:
  url: ${DB_URL:jdbc:postgresql://localhost:5432/ordersdb_prod}
  username: ${DB_USERNAME:meli_user}
  password: ${DB_PASSWORD:meli2025}
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate:
    ddl-auto: validate
    show-sql: false
server:
 port: 8082